### ISSUE TITLE
Error with catkin build

### ISSUE THREAD

**Issue by mahdi65** [methylDragon/pcl-reference-with-ros#1]
Got this error when catkin build the project:
`Error: declaration of ‘pcl::PCLPointCloud2 cloud’ shadows a parameter
   11 |   pcl::PCLPointCloud2 cloud;`

**Comment by ghost** [comment]
Hi, i tested the repo today, you need to change the content of the file minimal_pub_sub.cpp by:

#include <ros/ros.h>
// PCL specific includes
#include <sensor_msgs/PointCloud2.h>
#include <pcl_conversions/pcl_conversions.h>
#include <pcl/point_cloud.h>
#include <pcl/point_types.h>

ros::Publisher pub;

void cloud_cb (const sensor_msgs::PointCloud2ConstPtr& input)
{
  // Create a container for the data.
  sensor_msgs::PointCloud2 output;

  // Do data processing here...
  output = *input;

  // Publish the data.
  pub.publish (output);
}

int
main (int argc, char** argv)
{
  // Initialize ROS
  ros::init (argc, argv, "ros_pcl_minimal_pub_sub");
  ros::NodeHandle nh;

  // Create a ROS subscriber for the input point cloud
  ros::Subscriber sub = nh.subscribe ("camera/depth/points", 1, cloud_cb);

  // Create a ROS publisher for the output point cloud
  pub = nh.advertise<sensor_msgs::PointCloud2> ("test_output", 1);

  // Spin
  ros::spin ();
}

At least it worked fine for me. It is in this [link](http://wiki.ros.org/pcl/Tutorials)
You need to install the following dependencies:

`sudo apt install ros-melodic-pcl-ros
sudo apt install pcl-tools
sudo apt-get install libatlas-base-dev
sudo apt install ros-melodic-gazebo-ros ros-melodic-gazebo-plugins ros-melodic-gazebo-ros-pkgs ros-melodic-gazebo-ros-control
sudo apt install ros-melodic-octomap ros-melodic-octomap-ros ros-melodic-octomap-server ros-melodic-octomap-msgs ros-melodic-octomap-rviz-plugins`

**Comment by mahdi65** [comment]
@javiermov  Thanks a lot, that addressed the issue. I tried it on ROS Noetic. For the record if somebody is using Noetic they should update the "pcl_tester.launch" by changing ".../xacro.py" to "xacro" and the folder name "Starter Code" to something like "Starter_Code".
